'copy to people mirror only on tags':
  script:
  - git submodule update --init
  - ls -l
  - '# detect last tag of repo, if this build is a tag, so we can upload archive at
    the end'
  - VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
  - echo $VERSION
  - '#remove previous archive (if exists)'
  - rm -f fusioninventory-for-glpi_$VERSION.tar.gz
  - ''
  - '# prepare archive'
  - git archive --format=tar --prefix=fusioninventory/ $VERSION | gzip > fusioninventory-for-glpi_$VERSION.tar.gz
  - ''
  - '# copy to mirror'
  - scp fusioninventory-for-glpi_$VERSION.tar.gz root@people.teclib.net:/home/glebouder/public_html/mirror
  - ''
  - '# fix rights'
  - ssh root@people.teclib.net chown glebouder:users /home/glebouder/public_html/mirror/fusioninventory-for-glpi_$VERSION.tar.gz
  - fi
  tags: 
  except:
  - master
  only:
  - tags

