stages:
  - deploy
copy_to_mirror:
  script:
   - pwd
   - ls -l
   - '# detect last tag of repo, if this build is a tag, so we can upload archive at the end'
   - VERSION=$CI_COMMIT_TAG
   - echo $VERSION
   - '# prepare filename'
   - FI_FILENAME=fusioninventory-for-glpi_$VERSION.tar.gz
   - '# remove previous archive (if exists)'
   - rm -f $FI_FILENAME
   - '# prepare archive'
   - git archive --format=tar --prefix=fusioninventory/ $VERSION | gzip > $FI_FILENAME
   - '# copy to mirror'
   - scp $FI_FILENAME teclib@vm000139.paas.teclib.infra:/srv/releases/www/mirror
  stage: deploy
  except:
    - master
#  only:
#    - tags